server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8081/
          predicates:
            - Path=/api/**

# 网关的日志信息
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    # 设置应用的名称
    name: dy-api2
    qos-port: 2223
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22225
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry2
    address: nacos://101.133.130.46:8848
